dist: trusty

language: python

python:
    - '2.7'
    - '3.6'

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
      - python-matplotlib
      - python3-matplotlib
      - python-numpy
      - python3-numpy
      - python-scipy
      - python3-scipy

before_install:
  - pip install pytest pytest-cov

install:
  - pip install .

script:
  - cd test/
  - MPLBACKEND=Agg pytest --cov quadpy

after_success:
  - bash <(curl -s https://codecov.io/bash)
