version: 2

jobs:
  lint:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt update
      - run: apt install -y python3-pip
      - run: pip3 install -U black flake8
      - run: LC_ALL=C.UTF-8 black --check setup.py quadpy/ test/*.py
      - run: flake8 setup.py quadpy/ test/*.py
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      # <https://stackoverflow.com/a/44333806/353337>
      - run: DEBIAN_FRONTEND=noninteractive apt install tzdata
      - run: apt-get install -y git python3-pip python3-pybind11 libeigen3-dev python3-vtk7
      - run: pip3 install -U pytest pytest-cov
      - checkout
      - run: pip3 install -r test_requirements.txt
      - run: pip3 install .[all]
      # The tests
      - run: cd test/ && MPLBACKEND=Agg pytest --cov quadpy
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
