version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip3 install -U black flake8 --user
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:3.7
    steps:
      # <https://stackoverflow.com/a/44333806/353337>
      - run: DEBIAN_FRONTEND=noninteractive sudo apt-get install tzdata
      # eigen3 for accupy
      - run: sudo apt-get install -y libeigen3-dev python3-vtk7
      - run: pip3 install -U pytest pytest-cov --user
      - checkout
      - run: pip3 install -r test_requirements.txt --user
      - run: pip3 install .[all] --user
      # The tests
      - run:
          command: pytest --cov quadpy
          working_directory: test/
          environment:
            MPLBACKEND: Agg
      # submit to codecov
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
